export default {
  SPLASH: 'Splash',
  AUTH_NAVIGATION: 'AuthNavigation',
  LOGIN: 'Login',
  REGISTER: 'Register',
  MAIN_DRAWER: 'MainDrawer',
  DASHBOARD: 'Dashboard',
  DEPOSIT: 'Deposit',
  WITHDRAW: 'Withdraw',
  DOCUMENTS: 'Documents',
  TRADING_INFO: 'TradingInfo',
  TRANSACTIONS: 'Transactions',
  TWO_FACTOR: 'TwoFactor',
  FORGOT_PASSWORD: 'ForgotPassword',
  COUNTRY_LIST: 'CountryList',
};
