export default {
  NO_INTERNET_CONNECTION: 'Your internet connection has got lost or is poor. Please check.',
  LOGIN_TO_YOUR_ACCOUNT: 'Login to Your Account',
  ENTER_YOUR_EMAIL: 'Enter your email to receive a reset password link',
  EMAIL_ADDRESS: 'Email Address',
  PASSWORD: 'Password',
  LOGIN: 'Login',
  FORGOT_YOUR_PASSWORD: 'Forgot your password?',
  BACK_TO_LOGIN: 'Back to login',
  DONOT_HAVE_ACCOUNT: "Don't have account? ",
  SIGN_UP: 'Sign up',
  REGISTER: 'Register',
  FIRST_NAME: 'First Name',
  LAST_NAME: 'Last Name',
  EMAIL: 'Email',
  PHONE: 'Phone',
  I_DECLARE: 'I declare that :',
  DECLARE_TEXT: 'I am over 18 and read and understood to the',
  TERMS_CONDITION: ' Terms & Conditions ,',
  CLIENT_AGREEMENT: ' Client Agreements',
  DECLARE_TEXT_3: ' and disclosures',
  US_CITIZEN: 'I am not a U.S. citizen, nor have any tax obligations in the U.S.S',
  AGREE: 'I agree to receive regular promotional information',
  SUBMIT: 'Submit',
  ALREADY_ACCOUNT: 'Already have an account ?',
  LOGIN_HERE: ' Log in here',
  DASHBOARD: 'Dashboard',
  DEPOSIT: 'Deposit',
  WITHDRAW: 'Withdraw',
  TRADING_INFO: 'Trading Info',
  TRANSACTION_HISTORY: 'Transaction History',
  DOCUMENTS: 'Documents',
  TWO_FACTOR_AUTHENTICATION: 'Two-Factor Authentication',
  HELLO: 'Hello',
  REQUEST_CALLBACK: 'Request a Callback',
  REFER_FRIEND: 'Refer a Friend',
  SUPPORT_EMAIL: 'support@company.com',
  ACTIVE_ACCOUNTS: 'Your Active Accounts',
  ACCOUNT_NUMBER: 'Account number',
  WITHDRAW_FUNDS: 'Withdraw Funds',
  ADD_FUNDS: 'Add Funds',
  NOTE_CRM:
    'Please keep in mind that all withdrawal requested at CRM1 are handled within up to 7 days.',
  AVAILABLE_FUNDS: 'Available Funds',
  SELECT: 'Select',
  WITHDRAW_AMOUNT: 'Withdraw Amount',
  INITIAL_AMOUNT: '0.00',
  ADDRESS: 'Address',
  SUBMIT_REQUEST: 'Submit Request',
  MY_WITHDRAWL_REQUEST: 'My Withdrawal Requests',
  TRADING_ACCOUNT: 'Trading Account',
  REQUESTED_AMT: 'Requested Amount',
  APPROVED_AMT: 'Approved Amount',
  DATE: 'Date',
  ACCOUNT_SUMMARY: 'Account Summary',
  TRADE: 'Trade',
  TRANSFER: 'Transfer',
  BALANCE: 'Balance',
  EQUITY: 'Equity',
  CREDIT: 'Credit',
  OPEN_PL: 'Open P&L',
  CLOSE_PL: 'Close P&L',
  FREE_MARGIN: 'Free Margin',
  MARGIN_LEVEL: 'Margin Level',
  DEPOSIT_FUNDS: 'Deposit Funds',
  DEPOSIT_TO: 'Deposit to',
  SELECT_AN_ACCOUNT: 'Select an account',
  ACCEPTED_PAYMENT_METHODS: 'Accepted Payment Methods :',
  SECURED_PAYMENTS: 'Secured Payments :',
  MY_DEPOSITS: 'My Deposits',
  STATUS: 'Status',
  AMOUNT: 'Amount',
  TOTAL_RECORDS: 'Total Records:',
  TOTAL_PAGE: '| Total Page: 1 of 1',
  APPROVED: 'Approved',
  DECLINED: 'Declined',
  TRADING_INFORMATION: 'Trading Information',
  ACCOUNT_ID: 'Account ID',
  ORDER_ID: 'Order ID',
  SYMBOL: 'Symbol',
  OPEN_PRICE: 'Open Price',
  TWO_FACTOR_AUTHENTICATION: 'Two Factor Authentication',
  ENABLE_DISABLE_FA: 'Enable/ Disable the 2FA',
  WHAT_IS_2FA: 'What is the Two-Factor Authentication (2FA)?',
  FA_DEFINITION:
    'With 2-Step Verification (alos known as two-factor authentication), you add an extra layer of security to your account in case your password is stolen. After you set up 2-Step Verification, you’ll sign in to your account in two steps using:',
  LOGIN_CREDENTIALS: 'Login Credentials',
  GOOGLE_TOKEN: 'Google Authenticator Token',
  STEPS_FOR_2FA: 'Steps to turn on 2-Factor Authentication:',
  STEP_1: 'Turn on 2-Factor Authentication using toggle above',
  STEP_2: ' Install Google Authentication in your phone. Use these links below:',
  STEP_3: 'Logout from your account and then login again',
  STEP_4:
    'You will see a QR-Code Window. Scan or manually enter the code in the Authenticator app downloaded and Voila you are done.',
  FA_NOTE:
    'Now Every time you login, you need to enter the code as shown in your Google Authenticator.',
  FOR_IOS: 'For IOS',
  FOR_ANDROID: 'For Android',
  NOTE: 'Note :',
  TRANDING_ACCOUNT: 'Trading Account',
  TYPE: 'Type',
  TRANSACTION_STATUS: 'Transaction Status',
  FROM_TO_DATE: 'From/ To Date',
  CLOSE_PRICE: 'Close Price',
  PROFIT: 'Profit',
  VOLUME: 'Volume',
  ACTION_TYPE: 'Action Type',
  OPEN_TIME: 'Open Time',
  CLOSE_TIME: 'Close Time',
  COMMAND: 'Command',
  SL: 'SL',
  TP: 'TP',
  CREATION_TIME: 'Creation Time',
  LAST_UPDATED_ON: 'Last Updated On',
  LEVERAGE: 'Leverage',
  CARD_NUMBER: 'Card Number',
  CARD_NAME: 'Card Name',
  EXPIRY_DATE: 'Expiry Date',
  AMOUNT: 'Amount',
  MM: 'MM',
  YY: 'YY',
  DEPOSIT_NOW: 'Deposit now',
  DOCUMENTS_UPLOAD: 'Documents Upload',
  DOCUMENT_CATEGORY: 'Document Category',
  DOCUMENT_TYPE: 'Document type',
  DOCUMENT_FRONT: 'Document Front',
  NO_FILE_SELECTED: 'No file selected',
  UPLOAD_FILE: 'Upload File',
  DOCUMENT_SIZE: '(Max size 4MB, Allowed formats: JPEG, LPG, PNG or PDF) ',
  DOCUMENT_NAME: 'Document Name',
  DOCUMENT_STATUS: 'Document Status',
  FRONT_IMAGE: 'Front Image',
  DOCUMENT_BACK: 'Document Back',
  BACK_IMAGE: 'Back Image',
  ESIGN: 'ESIGN',
  APPROVAL_DATE: 'Approval Date',
  TAKE_IMAGE: 'Take Image',
  UPLOAD_FROM_GALLERY: 'Upload From Gallery',
  FROM: 'From',
  TO: 'To',
  COMMENT: 'Comment',
  SEARCH: 'Search',
};
